#!/usr/bin/env node
var url = require('url');
var dgram = require('dgram');

var uri = url.parse(process.argv[2]);
var ip = uri.hostname;
var port = uri.port;

var socket = dgram.createSocket('udp4');
socket.bind(port, function() {
    socket.addMembership(ip);

    setInterval(function() {
        var buf = new Buffer('test message ' + (new Date).toISOString());
        socket.send(buf, 0, buf.length, port, ip);
    }, 1000);
});

